name: 'Terraform CI/CD'

on:
  push: 
    branches:
     - main
     - feature/*
  pull_request: 
    branches:
      - main

env:
  TF_IN_AUTOMATION: true
  # Azure authentication
  ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
   # Terraform backend variables
  RESOURCE_GROUP_NAME: ${{ vars.RESOURCE_GROUP_NAME }}
  STORAGE_ACCOUNT_NAME: ${{ vars.STORAGE_ACCOUNT_NAME }}
  CONTAINER_NAME: ${{ vars.CONTAINER_NAME }}
  KEY: ${{ vars.KEY }}

jobs:
  validate:
    name: 'Terraform Validate and Plan'
    runs-on: ubuntu-latest
    if: startswith(github.ref, 'refs/heads/feature/')
    steps: 

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with: 
        terraform_version: latest
    
    - name: Terraform Init 
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.8
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: "./Infrastructure"
    
    - name: Terraform Validate
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.8
        tf_actions_subcommand: 'validate'
        tf_actions_working_dir: "./Infrastructure"

    - name: Terraform Format
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.8
        tf_actions_subcommand: 'fmt'
        tf_actions_working_dir: "./Infrastructure"
    
    - name: Terraform Plan (Feature Branch)
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.8
        tf_actions_subcommand: 'plan'
        tf_actions_working_dir: "./Infrastructure"
  
  deploy:
    name: 'Deploy Infrastructure To Azure'
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: latest
    
    - name: Terraform Init 
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.8
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: "./Infrastructure"
    
    - name: Terraform Plan (Feature Branch)
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.8
        tf_actions_subcommand: 'plan'
        tf_actions_working_dir: "./Infrastructure"

    - name: Terraform Apply 
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.8
        tf_actions_subcommand: 'apply'
        tf_actions_working_dir: "./Infrastructure"